---
title: "Projects"
---

In the summer of 2020 I took GEOG 176A, a GIS course based in R. I worte some code, and did some cool data science.I gradually learned how to review Rmarkdown syntax in both knit and Rmd format. I build my own website including text, images, hyperlinks, web theme, navbar, and icons. I developed my own content in my website with my personal information and published them on Github. It was really new to me, but I enjoyed this process a lot.

## [Building a project website](index.html)

- In this assignment we built a simple website with Github Pages 
- Includes basic information and a github repo for access to all the code.
- Look at how high quality my work is! <i class="fa fa-american-sign-language-interpreting" aria-hidden="true"></i>

## [Lab 01: Data Science Workflows](https://Vialawaila.github.io/)

- Use Rmarkdown and Github Pages to author a static website
What I learned:
- Rmarkdown formating
- Project organization
- HTML/CSS
- Local/remote datasets

<br>

## [Lab 02: Data Wrangling](https://Vialawaila.github.io/geog-176A-labs/lab-02.html)

- Visualize and wrangle real-time COVID-19 data maintained by the New York Times
What I learned:
- data wrangling and visualization
- Frame manipulation
- Joining datasets.

<br>

## [Lab 03: Projections, Distances, and Mapping](https://Vialawaila.github.io/geog-176A-labs/lab-03.html)

- Replicate the ACLU assessment that 2/3 of the USA population lives within the 100 mile “Border Zone” 
What I learned:
- Simple feature objects
- Geos measures
- Combines/unions
- Coordinate references systems
- Distance measurements

<br>

## [Lab 04: Tesselations, Spatial Joins, and Point-in-Polygon](https://Vialawaila.github.io/geog-176A-labs/lab-04.html)

- National Dams Inventory: explore the distribution of dams (and dam purpose) across the USA and challenges with the MAUP
What I learned:
- Geometry simplication
- Centroid generation
- Tesselations

<br>

## [Lab 05: Raster Analysis](https://Vialawaila.github.io/geog-176A-labs/lab-05.html)

- Detect and analyze a flood event near Palo, Iowa
What I learned:
- Multiband raster files
- Extraction and classification 
- Draw conclusions from the data

<br>

## [Lab 06: Terrain Analysis](https://Vialawaila.github.io/geog-176A-labs/lab-06.html)

- Generate a Height Above Nearest Drainage layer for the Mission Creek watershed, and convert this layer into a Flood Inudation Map (FIM) Library complete with structural damage assessment.
What I learned:
- Whitebox
- Data generation
- GIF
